In [126]:
import numpy as np
from numpy import random
import os
import pandas as pd

In [4]:
v = np.array([1,2,3,4])
M = np.array([[1,2],[3,4]])

In [10]:
print(type(v))
print(type(M))
print(v.shape)
print(M.shape)
print(M.size)
print(np.shape(M))
print(np.size(M))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4,)
(2, 2)
4
(2, 2)
4


In [13]:
M.dtype
#Below will be error due to type issue; since type of matrix is set to int
#M[0,0] = "Hello"

#Setting datatype explicity
M = np.array([[1,2], [3,4]], dtype = complex)
print(M)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


#### Array generating functions

In [23]:
a1 = np.arange(-1, 1, 0.1)
print(a1)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [25]:
a2 = np.linspace(0, 10, 25) #Divides the range into 25 equal segments
print(a2)

[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]


In [30]:
a3 = np.logspace(0, 10, 10, base = np.e)
print(a3)

[1.00000000e+00 3.03773178e+00 9.22781435e+00 2.80316249e+01
 8.51525577e+01 2.58670631e+02 7.85771994e+02 2.38696456e+03
 7.25095809e+03 2.20264658e+04]


In [32]:
x, y = np.mgrid[0:5, 0:5]
print(x)
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [34]:
#uniform distribution over [0, 1)
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
random.rand(5,5)

array([[0.33977954, 0.52507936, 0.94571306, 0.2322954 , 0.63039041],
       [0.58245984, 0.19141024, 0.27649642, 0.16723337, 0.1208744 ],
       [0.38463047, 0.74013359, 0.88489655, 0.50527884, 0.2791054 ],
       [0.55877032, 0.31532247, 0.77186314, 0.76716935, 0.2895587 ],
       [0.63230043, 0.5587735 , 0.06673499, 0.29257417, 0.69473725]])

In [35]:
# standard normal distributed random numbers
random.randn(5,5)

array([[-1.72247295, -0.26713408, -0.26089483,  0.68582493,  0.117714  ],
       [-1.25332595,  0.95600878, -0.416221  , -0.58826989, -0.80523721],
       [-0.00756688,  0.38101483, -2.01327476,  1.06654171, -0.10130112],
       [-1.37504897,  2.16948111,  0.77882742,  1.0333799 ,  1.05429857],
       [-0.83189851, -0.22339049, -0.89833871, -0.59168087,  0.28527185]])

In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
print(A)
A[::2, ::2] # M[lower:upper:step]

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [53]:
B = np.array([n for n in range(5)])
print(B)

[0 1 2 3 4]


In [56]:
x = np.arange(0, 10, 0.5)
print(x)
mask = (5 < x) * (x < 7.5)
print(x[mask])
indices = np.where(mask)
print(indices)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[5.5 6.  6.5 7. ]
(array([11, 12, 13, 14]),)


In [63]:
print(A)
print(np.diag(A)) # diagnol
print(np.diag(A, -1)) # subdiagnol
print(np.diag(A, -2))

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[ 0 11 22 33 44]
[10 21 32 43]
[20 31 42]


##  Scalar-array operations

In [65]:
v1 = np.arange(0, 5)
print(v1)
print(v1 * 2)
print(v1 + 2)

[0 1 2 3 4]
[0 2 4 6 8]
[2 3 4 5 6]


In [68]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

In [71]:
A*A, A+A, A-A # When A is an array, element wise operation, A*A gives element wise multiplication; 

(array([[   0,    1,    4,    9,   16],
        [ 100,  121,  144,  169,  196],
        [ 400,  441,  484,  529,  576],
        [ 900,  961, 1024, 1089, 1156],
        [1600, 1681, 1764, 1849, 1936]]), array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]))

In [72]:
print(v1*v1)

[ 0  1  4  9 16]


In [73]:
A.shape, v1.shape

((5, 5), (5,))

In [76]:
print(A*v1) #If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:
print(A)
print(v1)

[[  0   1   4   9  16]
 [  0  11  24  39  56]
 [  0  21  44  69  96]
 [  0  31  64  99 136]
 [  0  41  84 129 176]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[0 1 2 3 4]


## Matrix algebra

In [84]:
print(np.dot(A,A)) 
print('\n')
print(np.dot(A, v1))
print('\n')
print(np.dot(v1, v1))

[[ 300  310  320  330  340]
 [1300 1360 1420 1480 1540]
 [2300 2410 2520 2630 2740]
 [3300 3460 3620 3780 3940]
 [4300 4510 4720 4930 5140]]


[ 30 130 230 330 430]


30


In [86]:
M = np.matrix(A) #cast the array objects to the type matrix
v = np.matrix(v1).T # make it a column vector matrix

In [89]:
print(v)
print(M*M) #M - matrix format; A array format of same info
print(M*v)
print('\n')
print(v.T*v) # similar to dot product, but output is a mtrix

[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 300  310  320  330  340]
 [1300 1360 1420 1480 1540]
 [2300 2410 2520 2630 2740]
 [3300 3460 3620 3780 3940]
 [4300 4510 4720 4930 5140]]
[[ 30]
 [130]
 [230]
 [330]
 [430]]


[[30]]


In [98]:
C = np.matrix([[1j, 2j], [3j, 4j]])
print(C) 
print('\n')
print(np.conjugate(C))
print('\n')
print(np.transpose(C))
print('\n')
print(C.H) #Hermitian conjugate: transpose + conjugate

[[0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j]]


[[0.-1.j 0.-2.j]
 [0.-3.j 0.-4.j]]


[[0.+1.j 0.+3.j]
 [0.+2.j 0.+4.j]]


[[0.-1.j 0.-3.j]
 [0.-2.j 0.-4.j]]


In [104]:
print(np.real(C)) 
print('\n')
print(np.imag(C)) 
print('\n')
print(C+1)
print('#Returns angle of complex number in radians')
print(np.angle(C+1)) 
print('#Returns angle of complex number in degreesn')
print(np.angle(C+1, deg = True)) 
print('For complex input, a + ib, the absolute value is \sqrt{ a^2 + b^2 }.')
print(np.absolute(C))

[[0. 0.]
 [0. 0.]]


[[1. 2.]
 [3. 4.]]


[[1.+1.j 1.+2.j]
 [1.+3.j 1.+4.j]]
#Returns angle of complex number in radians
[[0.78539816 1.10714872]
 [1.24904577 1.32581766]]
#Returns angle of complex number in degreesn
[[45.         63.43494882]
 [71.56505118 75.96375653]]
For complex input, a + ib, the absolute value is \sqrt{ a^2 + b^2 }.
[[1. 2.]
 [3. 4.]]


## Matrix Computations

In [108]:
#Inverse of a Matrix
print(np.linalg.inv(C)) 
print(C.I)
print(C.I * C)

[[0.+2.j  0.-1.j ]
 [0.-1.5j 0.+0.5j]]
[[0.+2.j  0.-1.j ]
 [0.-1.5j 0.+0.5j]]
[[1.00000000e+00+0.j 0.00000000e+00+0.j]
 [1.11022302e-16+0.j 1.00000000e+00+0.j]]


In [110]:
#Determinant
print(np.linalg.det(C))
print(np.linalg.det(C.I))

(2.0000000000000004+0j)
(0.4999999999999997+0j)


In [119]:
d = np.arange(0, 10)
print(d)
print(np.sum(d))
print(np.prod(d+1))
print(np.cumsum(d))
print(np.cumprod(d+1))

[0 1 2 3 4 5 6 7 8 9]
45
3628800
[ 0  1  3  6 10 15 21 28 36 45]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [124]:
print(np.diag(A))
print(np.trace(A)) #same as diag(A).sum()

[ 0 11 22 33 44]
110


In [131]:
os.chdir('/Users/suma/Trading Setup/Data/')
df = pd.read_excel('Linear Model Data - Nifty.xlsx' ,'Sheet2_msno', index_col = [0])
np_df = df.values
np_df[:3,]

array([[-5.77100000e+02,  1.86140000e+02,  1.06635000e+04,
        -8.40000000e-03, -8.45108333e-03, -2.47000000e-02,
        -2.50325962e-02,  6.99850000e+01, -2.40000000e-03,
        -2.35487318e-03,  2.35110000e+03, -2.71000000e-02,
        -2.74865659e-02,  1.07300000e+04,  6.23622638e-03,
         6.21686159e-03],
       [ 1.34140000e+02, -4.88550000e+02,  1.07540000e+04,
        -1.81000000e-02, -1.82169170e-02, -2.80000000e-03,
        -2.77735096e-03,  7.01400000e+01,  2.30000000e-03,
         2.28375777e-03,  2.41662000e+03, -2.06000000e-02,
        -2.08032007e-02,  1.06635000e+04, -8.40000000e-03,
        -8.45108333e-03],
       [-3.86440000e+02,  8.79600000e+01,  1.09517000e+04,
        -1.40000000e-03, -1.42342284e-03, -3.99000000e-02,
        -4.07603593e-02,  6.99800000e+01, -4.20000000e-03,
        -4.24931838e-03,  2.46742000e+03, -1.58000000e-02,
        -1.58977934e-02,  1.07540000e+04, -1.81000000e-02,
        -1.82169170e-02]])

### Reshaping resizing and stacking arrays

In [136]:
n, m = A.shape
B = A.reshape((1, n*m))
print(A)
print(B)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
[[ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]]


##### Changes to B are carried to A

In [138]:
B[0, 0:5] = 5
print(B)
print(A)

[[ 5  5  5  5  5 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
  44]]
[[ 5  5  5  5  5]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


### reshape vs flatten

In [142]:
C = A.flatten()
print(C)

[ 5  5  5  5  5 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]


In [143]:
C[0:5] = 10
print(C)
print(A)

[10 10 10 10 10 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]
[[ 5  5  5  5  5]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


#### Adding new dimension: newaxis

In [151]:
v = np.array([1,2,3])
v.shape

#changing vector to matrix
m1 = v[:, np.newaxis]
print(m1)
print(m1.shape)

m2 = v[np.newaxis, :]
print(m2)
print(m2.shape)


[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)


#### Stacking and repeating arrays

In [153]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [156]:
print(np.repeat(a,3))

[1 1 1 2 2 2 3 3 3 4 4 4]


In [157]:
print(np.tile(a,3))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [165]:
#concatenate
b = np.array([[5,6]])
print(b)
print(np.concatenate((a,b), axis = 0))

[[5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [166]:
print(np.concatenate((a,b.T), axis = 1))

[[1 2 5]
 [3 4 6]]


In [169]:
print(np.vstack((a,b)))
print(np.hstack((a,b.T)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


#### Copy and Deepcopy

In [174]:
A = np.array([[1,2], [3,4]])
print(A)
B = A
B[0,0] = 10
print(B)
print(A)

[[1 2]
 [3 4]]
[[10  2]
 [ 3  4]]
[[10  2]
 [ 3  4]]


In [175]:
B = np.copy(A)

In [176]:
B[0,0] = 20
print(B)
print(A)

[[20  2]
 [ 3  4]]
[[10  2]
 [ 3  4]]


#### Iterating over array elements

In [178]:
v = np.array([1, 2, 3, 4])

for elements in v:
    print(elements)

1
2
3
4


In [180]:
M = np.array([[1,2] , [3,4]])
for row in M:
    print("row:", row)
    for elements in row:
        print(elements)

row: [1 2]
1
2
row: [3 4]
3
4


#### Enumerate function to obtain both the element and its index in the for loop 

In [183]:
for row_id, row in enumerate(M):
    print("row ID:", row_id, "row", row)
    for element_id, element in enumerate(row):
        print("element ID:",element_id, "element:", element)

row ID: 0 row [1 2]
element ID: 0 element: 1
element ID: 1 element: 2
row ID: 1 row [3 4]
element ID: 0 element: 3
element ID: 1 element: 4


#### Arrays in Conditions

In [186]:
print(M)
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

[[1 2]
 [3 4]]
no element in M is larger than 5


In [187]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5
